[package]
name = "ananse"
version = "0.1.0"
description = "A simple peer-to-peer gossip protocol handler"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
bincode = "1.3.2"
hhmmss = "0.1.0"
log = "0.4.14"
message-io = "0.11.1"
petname = "1.1.0"
serde = "1.0.125"
